In [12]:
!pip install pandas
!pip install numpy

import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /home/mkosemes/jupy-env/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /home/mkosemes/jupy-env/lib/python3.12/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mkosemes/jupy-env/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/mkosemes/jupy-env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /home/mkosemes/jupy-env/lib/python3.12/site-packages (2.4.2)

### Chargement des ensemble de donnees

In [5]:
df = pd.read_csv("Data/airbnb_exam_dataset.csv")
df1 = pd.read_csv("Data/supermarket_sales_exam_dataset.csv")
df2 =pd.read_csv("Data/taxi_trips_exam_dataset.csv")

## INSPECTION DES DONNÉES

In [6]:
df.head()

,listing_id,neighbourhood,room_type,price,minimum_nights,number_of_reviews,availability_365,reviews_per_month
0,1,Bronx,Shared room,224,5,276,155,5.56
1,2,Staten Island,Private room,324,6,197,48,2.18
2,3,Queens,Entire home,259,5,69,336,4.72
3,4,Staten Island,Shared room,108,5,111,83,2.89
4,5,Staten Island,Entire home,86,4,3,360,0.73

In [7]:
df1.head()

,invoice_id,city,product_category,unit_price,quantity,customer_type,payment,total
0,1,Dakar,Food,97.27,13,Normal,Cash,1264.51
1,2,Lagos,Cosmetics,18.48,13,Member,Card,240.24
2,3,Abidjan,Food,41.77,6,Normal,Cash,250.62
3,4,Nairobi,Beverage,103.89,12,Normal,Card,1246.68
4,5,Lagos,Beverage,19.44,10,Normal,Mobile,194.40

In [8]:
df2.head()

,trip_id,pickup_zone,dropoff_zone,distance_km,duration_min,fare_amount,tip_amount,passenger_count,payment_type
0,1,Brooklyn,Downtown,23.15,52.3,77.89,1.08,1,cash
1,2,Brooklyn,Harlem,12.69,37.3,30.52,10.24,1,card
2,3,Airport,Airport,15.55,33.4,41.67,3.63,3,card
3,4,Harlem,Downtown,19.36,52.4,20.51,10.71,3,cash
4,5,Midtown,Harlem,5.20,54.8,51.20,12.34,4,cash

In [16]:
print(f"Premier dataset (lignes, colonnes) : {df.shape}\n"
      f"Second dataset  (lignes, colonnes) : {df1.shape}\n"
      f"Troisième dataset (lignes, colonnes) : {df2.shape}")

Premier dataset (lignes, colonnes) : (220, 8)
Second dataset  (lignes, colonnes) : (260, 8)
Troisième dataset (lignes, colonnes) : (300, 9)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   listing_id         220 non-null    int64
 1   neighbourhood      220 non-null    str
 2   room_type          220 non-null    str
 3   price              220 non-null    int64
 4   minimum_nights     220 non-null    int64
 5   number_of_reviews  220 non-null    int64
 6   availability_365   220 non-null    int64
 7   reviews_per_month  220 non-null    float64
dtypes: float64(1), int64(5), str(2)
memory usage: 13.9 KB

In [18]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   invoice_id        260 non-null    int64
 1   city              260 non-null    str
 2   product_category  260 non-null    str
 3   unit_price        260 non-null    float64
 4   quantity          260 non-null    int64
 5   customer_type     260 non-null    str
 6   payment           260 non-null    str
 7   total             260 non-null    float64
dtypes: float64(2), int64(2), str(4)
memory usage: 16.4 KB

In [19]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   trip_id          300 non-null    int64
 1   pickup_zone      300 non-null    str
 2   dropoff_zone     300 non-null    str
 3   distance_km      300 non-null    float64
 4   duration_min     300 non-null    float64
 5   fare_amount      300 non-null    float64
 6   tip_amount       300 non-null    float64
 7   passenger_count  300 non-null    int64
 8   payment_type     300 non-null    str
dtypes: float64(4), int64(2), str(3)
memory usage: 21.2 KB

In [24]:
df.isna().sum()

listing_id           0
neighbourhood        0
room_type            0
price                0
minimum_nights       0
number_of_reviews    0
availability_365     0
reviews_per_month    0
dtype: int64

In [22]:
df1.isna().sum()

invoice_id          0
city                0
product_category    0
unit_price          0
quantity            0
customer_type       0
payment             0
total               0
dtype: int64

In [23]:
df2.isna().sum()

trip_id            0
pickup_zone        0
dropoff_zone       0
distance_km        0
duration_min       0
fare_amount        0
tip_amount         0
passenger_count    0
payment_type       0
dtype: int64

In [27]:
print(f"Le nombre de valeur manquante dans le premier datset est de : {df.duplicated().sum()}")
print(f"Le nombre de valeur manquante dans le premier datset est de : {df1.duplicated().sum()}")
print(f"Le nombre de valeur manquante dans le premier datset est de : {df2.duplicated().sum()}")

Le nombre de valeur manquante dans le premier datset est de : 0
Le nombre de valeur manquante dans le premier datset est de : 0
Le nombre de valeur manquante dans le premier datset est de : 0

In [28]:
num_df = len(df.select_dtypes('number').columns)
cat_df = len(df.select_dtypes('object').columns)
print(f"DF1 - Numériques: {num_df} | Catégorielles: {cat_df}")

DF1 - Numériques: 6 | Catégorielles: 2

/tmp/ipykernel_494800/630991301.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_df = len(df.select_dtypes('object').columns)

In [32]:
num_df1 = len(df1.select_dtypes('number').columns)
cat_df1 = len(df1.select_dtypes('object').columns)
print(f"DF1 - Numériques: {num_df1} | Catégorielles: {cat_df1}")

DF1 - Numériques: 4 | Catégorielles: 4

/tmp/ipykernel_494800/4079897433.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_df1 = len(df1.select_dtypes('object').columns)

In [33]:
num_df2 = len(df2.select_dtypes('number').columns)
cat_df2 = len(df2.select_dtypes('object').columns)
print(f"DF1 - Numériques: {num_df2} | Catégorielles: {cat_df2}")

DF1 - Numériques: 6 | Catégorielles: 3

/tmp/ipykernel_494800/1845937606.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_df2 = len(df2.select_dtypes('object').columns)

In [34]:
var_df = df.select_dtypes('number').var().idxmax()
print(f"DF1 - Plus grande variance : {var_df}")

DF1 - Plus grande variance : price

In [35]:
var_df1 = df1.select_dtypes('number').var().idxmax()
print(f"DF1 - Plus grande variance : {var_df1}")

DF1 - Plus grande variance : total

In [36]:
var_df2 = df2.select_dtypes('number').var().idxmax()
print(f"DF1 - Plus grande variance : {var_df2}")

DF1 - Plus grande variance : trip_id

#### Identification de 2 observations suspectes ou aberrantes dans chaque dataset.

In [37]:
print("DF - 2 Observations suspectes :")
print(df.nlargest(2, var_df))

DF1 - 2 Observations suspectes :
    listing_id neighbourhood    room_type  price  minimum_nights  \
14          15         Bronx  Entire home   1500               6
38          39     Manhattan  Entire home   1200               2

    number_of_reviews  availability_365  reviews_per_month
14                228               256               5.27
38                 46               263               6.63

In [38]:
print("DF1 - 2 Observations suspectes :")
print(df1.nlargest(2, var_df1))

DF1 - 2 Observations suspectes :
     invoice_id     city product_category  unit_price  quantity customer_type  \
157         158    Dakar      Electronics      112.05        14        Member
234         235  Nairobi        Cosmetics      111.86        14        Normal

    payment    total
157    Cash  1568.70
234  Mobile  1566.04

In [39]:
print("DF2 - 2 Observations suspectes :")
print(df2.nlargest(2, var_df2))

DF2 - 2 Observations suspectes :
     trip_id pickup_zone dropoff_zone  distance_km  duration_min  fare_amount  \
299      300     Midtown     Downtown         2.93          23.0        52.23
298      299    Downtown     Brooklyn         4.20          14.1        49.35

     tip_amount  passenger_count payment_type
299       14.11                3         card
298        1.04                2         card